/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwaredoug.solr.stats;

import org.apache.solr.core.PluginInfo;
import org.apache.solr.handler.component.ResponseBuilder;
import org.apache.solr.handler.component.ShardRequest;
import org.apache.solr.handler.component.ShardResponse;
import org.apache.solr.request.SolrQueryRequest;
import org.apache.solr.search.SolrIndexSearcher;
import org.apache.solr.search.stats.LocalStatsCache;
import org.apache.solr.search.stats.LocalStatsSource;
import org.apache.solr.search.stats.StatsCache;
import org.apache.solr.search.stats.StatsSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.invoke.MethodHandles;
import java.util.List;

public class ManagedStatsCache extends LocalStatsCache {
    private static final Logger log = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

    public ManagedStatsCache() {
        super();
        log.info("Loading ManagedStatsCache");
    }

    @Override
    protected StatsSource doGet(SolrQueryRequest req) {
        StatsSource fallback = new LocalStatsSource(statsCacheMetrics);
        return new ManagedStatsSource(fallback, req.getSchema());
    }

    // by returning null we don't create additional round-trip request.
    @Override
    protected ShardRequest doRetrieveStatsRequest(ResponseBuilder rb) {
        // already incremented the stats - decrement it now
        return null;
    }

    @Override
    public void init(PluginInfo info) {
    }

    // by returning null we don't create additional round-trip request.

    @Override
    public void mergeToGlobalStats(SolrQueryRequest req,
                                   List<ShardResponse> responses) {
        if (log.isDebugEnabled()) {
            log.debug("## MTGD {}", req);
        }
    }

    @Override
    public void returnLocalStats(ResponseBuilder rb, SolrIndexSearcher searcher) {
        log.debug("## RLD {}", rb.req);
    }

    @Override
    public void receiveGlobalStats(SolrQueryRequest req) {
        log.debug("## RGD {}", req);
    }

    @Override
    public void sendGlobalStats(ResponseBuilder rb, ShardRequest outgoing) {
        log.debug("## SGD {}", outgoing);
    }
}

