/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwaredoug.solr.stats;

import org.apache.solr.SolrTestCaseJ4;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class ManagedStatsTest extends SolrTestCaseJ4 {

    private ManagedStats managedStats;

    @Before
    public void setupStats() throws Exception {
        initCore("solrconfig.xml", "schema.xml", "build/resources/test/solr");
    }

    @After
    public void cleanup() {
        deleteCore();
    }

    @Test public void someLibraryMethodReturnsTrue() {
        System.out.println("Test!");
    }
}
